# Application Name
spring.application.name=backend

# Server Port
server.port=8080

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://yogeshwaransk2005_db_user:qqIU7EPQzep1iv7u@cluster0.krnkv6g.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0

# Logging
logging.level.org.springframework.security=DEBUG

# JWT Settings
jwt.secret=ChangeThisSecretKey123456789012345678901234567890
jwt.expiration=86400000

# File Upload Size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Frontend URL
frontend.url=https://chat-application-bay-delta.vercel.app