spring.application.name=backend

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}

logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

frontend.url=https://chat-application-bay-delta.vercel.app